### ISSUE TITLE
Complete crypto API

### ISSUE THREAD

**Issue by halorrr** [halorrr/lunchmoney-ruby#74]
Our crypto calls should all be fully operational any mirror the documentation https://lunchmoney.dev/#crypto

- [ ] Get `crypto` calls working
- [ ] Get `update_crypto` calls working
- [ ] Ensure crypto calls are well tested
- [ ] Add validations to crypto object
